version: "3"

services:

  backend-admin:
    container_name: backend-admin
    image: microedus/backend-admin:1.0
    build:
      context: ./backend-admin
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - microedus
    volumes:
      - ./backend-admin:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  backend-student:
    container_name: backend-student
    image: microedus/backend-student:1.0
    build:
      context: ./backend-student
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:debug
    ports:
      - 3001:3000
      - 9230:9229
    networks:
      - microedus
    volumes:
      - ./backend-admin:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  backend-datacenter:
    container_name: backend-datacenter
    image: microedus/backend-datacenter:1.0
    build:
      context: ./backend-datacenter
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:debug
    ports:
      - 3002:3000
      - 9231:9229
    networks:
      - microedus
    volumes:
      - ./backend-admin:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - microedus

  redis:
    image: "bitnami/redis:latest"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis"
    networks:
      - microedus

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /postgres:/data/postgres
    env_file:
      - .env
    networks:
      - microedus

volumes:
  redis_data:
    driver: local
networks:
  microedus: